# Generated by Django 3.1.4 on 2021-01-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="photos")),
                ("weight", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
        ),
    ]
